export const products = [
  { id: 'Ear1', name: 'Shiny Pink', price: 299 },
  { id: 'Ear2', name: 'RoseGold', price: 299 },
  { id: 'Ear3', name: 'Lavender Pop', price: 299 },
  { id: 'Ear4', name: 'Rosemoon', price: 299 },
  { id: 'Ear5', name: 'Shine Lavender', price: 299 },
  { id: 'Ear6', name: 'Rosy', price: 350 },
  { id: 'Ear7', name: 'Blush', price: 200 },
  { id: 'Ear8', name: 'Beige', price: 200 },
  { id: 'Ear9', name: 'Rush Pink', price: 299 },
  { id: 'Ear10', name: 'Gold', price: 299 },
  { id: 'Ear11', name: 'Scarlet', price: 350 },
  { id: 'Ear12', name: 'Golden', price: 350 },
  { id: 'Ear13', name: 'Pink Rose', price: 350 },
  { id: 'Ear14', name: 'Pistachio', price: 350 },
  { id: 'Ear15', name: 'Rosepearl', price: 200 },
  { id: 'Ear16', name: 'Justrose', price: 299 },
  { id: 'Ear17', name: 'Shine Rose', price: 350 },
  { id: 'Ear18', name: 'Yellow Bloom', price: 350 },
  { id: 'Ear19', name: 'Diamond Rose', price: 250 },
  { id: 'Ear20', name: 'Pinkish', price: 200 },
  { id: 'Ear21', name: 'Blooming', price: 200 },
  { id: 'Ear22', name: 'Orangish', price: 150 },
  { id: 'Ear23', name: 'Aurora', price: 150 },
  { id: 'Ear25', name: 'Velvet', price: 150 },
  { id: 'Ear26', name: 'Ocean', price: 170 },
  { id: 'Ear27', name: 'Petal Poetry', price: 250 },
  { id: 'Ear28', name: 'Twilight', price: 150 },
  { id: 'Ear29', name: 'Sunflower', price: 99 },
  { id: 'Ear30', name: 'Pink Water', price: 150 },
  { id: 'Ear31', name: 'Beads', price: 150 },
  { id: 'Ear32', name: 'Dancing Lavender', price: 299 },
];
